### PR TITLE
Updated to bevy 13.0

### PR DESCRIPTION
**Pull request by sardap**
- Updated to Bevy 13.0
- Added Compatibility table to readme

### CODE REVIEW

**Comment by cdsupina** [comment]
I ran the fishy example and noticed that the backgrounds were all greyscale. It looks your changes broke the functionality added with this PR: #22 

Could you try to fix this before we merge this?

Thanks for all of the work you have done so far.

**Comment by sardap** [comment]
@cdsupina Sorry for missing that I have added the sprite info backinto the SpriteSheetBundle. I noticed the colors look darker than the gif. But I also tested on the bevy 0.11 version and the colours are also darker there.

**Comment by ettoreleandrotognoli** [comment]
Hello @sardap @cdsupina 
When I added https://github.com/Corrosive-Games/bevy-parallax/pull/22 the colors were changed
I said something like "the final result don't have exactly the same colors"

**Review by ettoreleandrotognoli — APPROVED** [review]
LGTM

**Pull request merged**
