### PR TITLE
add repeat option to layer

### PR DESCRIPTION
**Pull request by ettoreleandrotognoli**
now it is possible to choose which axis to repeat, independently of the layer speed,
and how to repeat them with RepeatStrategy::( Same, Mirror )

Resolves https://github.com/Corrosive-Games/bevy-parallax/issues/26

### CODE REVIEW

**Comment by cdsupina** [comment]
I'm getting an error when I try to run any of the examples:

```
thread 'main' panicked at C:\Users\Carlo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\comment_strip_iter.rs:6:67:
called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
    (\/\/|\/\*|\*\/)
     ^^
error: unrecognized escape sequence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)
```

I don't think this is related to the specific change you made, but are you getting this as well?

**Comment by ettoreleandrotognoli** [comment]
Nop, the docs is working

**Comment by ettoreleandrotognoli** [comment]
Hello @odecay @cdsupina 

I changed the main algorithm, but I'm not sure if it is a better approach
As I wanted to add a mirror feature I had to change the generation of the children layers, they need to be a pair number
I'm not sure if I get all the math moving the textures, but I'm trying to move the not visible textures from one side to the other accordingly with the camera movement
I think that it is nice because I was able to remove a "magic number" the transition_factor

**Comment by cdsupina** [comment]
> I'm getting an error when I try to run any of the examples:
> 
> ```
> thread 'main' panicked at C:\Users\Carlo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\naga_oil-0.8.2\src\compose\comment_strip_iter.rs:6:67:
> called `Result::unwrap()` on an `Err` value: Syntax(
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> regex parse error:
>     (\/\/|\/\*|\*\/)
>      ^^
> error: unrecognized escape sequence
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> )
> ```
> 
> I don't think this is related to the specific change you made, but are you getting this as well?

solved this turns out my lock file was out of date

**Review by cdsupina — APPROVED** [review]
This is a great addition! Glad you were able to remove the magic number! 😅

**Pull request merged**
